"""commit

Revision ID: 4a4de1dc219c
Revises: 
Create Date: 2025-02-05 21:33:00.811153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a4de1dc219c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experimentos_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hiperparametros_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('id_metadados', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_metadados'], ['experimentos_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modelos_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['training_id'], ['experimentos_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modelos_table')
    op.drop_table('hiperparametros_table')
    op.drop_table('experimentos_table')
    # ### end Alembic commands ###
