"""commit1

Revision ID: cedefaeafe99
Revises: 4a4de1dc219c
Create Date: 2025-02-05 21:55:53.605142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cedefaeafe99'
down_revision: Union[str, None] = '4a4de1dc219c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modelos_table', sa.Column('name', sa.String(), nullable=False))
    op.add_column('modelos_table', sa.Column('category', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modelos_table', 'category')
    op.drop_column('modelos_table', 'name')
    # ### end Alembic commands ###
