"""commit01

Revision ID: e631d20d6b9f
Revises: 503c79381876
Create Date: 2025-01-19 16:44:25.593282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e631d20d6b9f'
down_revision: Union[str, None] = '503c79381876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models_table', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models_table', sa.Column('path', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
