"""innit

Revision ID: 00831190ed39
Revises: 
Create Date: 2025-01-14 00:31:07.212327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00831190ed39'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dados_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_perfil', sa.String(), nullable=False),
    sa.Column('nome_chapa', sa.String(), nullable=False),
    sa.Column('bitola_parafuso', sa.Integer(), nullable=False),
    sa.Column('material_chapa', sa.String(), nullable=False),
    sa.Column('distancia_s', sa.Float(), nullable=False),
    sa.Column('qntd_parafusos', sa.Integer(), nullable=False),
    sa.Column('fs', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stress_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block', sa.Float(), nullable=True),
    sa.Column('shear_plate', sa.Float(), nullable=True),
    sa.Column('plate_crush', sa.Float(), nullable=True),
    sa.Column('bolt_shear', sa.Float(), nullable=True),
    sa.Column('web_shear', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['dados_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stress_table')
    op.drop_table('dados_table')
    # ### end Alembic commands ###
